src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Appointment_Price__c</fullName>
        <label>Appointment Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Specializations</fullName>
        <active>true</active>
        <label>Specializations</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patients__c</referenceTo>
        <relationshipLabel>Care Plans</relationshipLabel>
        <relationshipName>Care_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patients__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patients Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MakeAppointmentControllerTest.cls
@IsTest
public with sharing class MakeAppointmentControllerTest {
    @testSetup
    static void setupTestData() {
        Id specializationRecordId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Specializations').getRecordTypeId();
        Account actRecord = new Account();
        actRecord.name = 'Test Account';
        actRecord.Appointment_Price__c = 100;
        actRecord.Type= 'Cardiology';
        actRecord.recordTypeId = specializationRecordId;
        insert actRecord;

        contact contactRecord = new contact();
        contactRecord.FirstName = 'Test';
        contactRecord.LastName = 'Test';
        contactRecord.Email = 'Test@test.com';
        contactRecord.accountId = actRecord.Id;
        insert contactRecord;

        Patients__c patient = new Patients__c();
        patient.First_Name__c = 'Pname';
        patient.Last_Name__c = 'PLast';
        patient.Email__c = 'Pname@gmail.com';
        insert patient;
    }
    
	static testMethod void getEventTest() {
        Test.setMock(HttpCalloutMock.class, new MakeAppointControllerMockResponse());
        String selectedDate = '2020-12-11';
        contact selectedDoctorVar = [Select Id , Email from Contact where email='Test@test.com'];
        
        String selectedSpecialization = 'Cardiology';
        
        string selectedDoctor = System.JSON.Serialize(selectedDoctorVar);
        List<MakeAppointmentController.appointmentDetails> evDetail = new List<MakeAppointmentController.appointmentDetails>();

        Test.startTest();
        MakeAppointmentController.getAppointmentPrice(selectedSpecialization);
        MakeAppointmentController.getDoctors('--Select--');
        evDetail =  MakeAppointmentController.getEvents(selectedDate, selectedDoctor);
        Test.stopTest();
        System.assert(evDetail != null);
    }
    static testMethod void bookAppointmentTest() {
        Test.setMock(HttpCalloutMock.class, new MakeAppointControllerMockResponse());
        String selectedDate = '2020-12-11';
        contact selectedDoctorVar = [Select Id , Email from Contact where email='Test@test.com'];
        Patients__c patient = [Select Id, Email__c from Patients__c where email__c='Pname@gmail.com'];
        
        String selectedDoctor = System.JSON.Serialize(selectedDoctorVar);
        String selectedPatient = patient.Id;
        String eventDetails = '{"endTime":"2020-12-09 11:00:00","endTimeDisplay":"11:00","isAvailable":true,"startTime":"2020-12-09 10:30:00","startTimeDisplay":"10:30"}';
        Test.startTest();
            MakeAppointmentController.bookAppointment(eventDetails, selectedDoctor, selectedPatient);
        Test.stopTest();
        case newCarePlan = [Select Id from Case where Patient__c =: id.valueOf(selectedPatient)];
        system.assert(newCarePlan != null);
    }
}